### ISSUE TITLE
Provide a way to know when GOAWAY had been sent during shutdown

### ISSUE THREAD

**Issue by ash2k** [grpc/grpc-go#6830]
### Use case(s) - what problem will this feature solve?

I have a server and a client. Client establishes a streaming response connection to the server and tries to always keep it open. Server responds when it has information to send. The connection can stay open for a long time (configurable) e.g. 1 hour.

Server does graceful shutdown by signaling all goroutines handling incoming connections and then calling `GracefulStop()`. The issue is that there is a race condition between client getting GOAWAY and re-establishing a connection:

1. Server initiates shutdown. Signals handlers.
1. RPC handler gets the signal, returns from the handler cleanly.
1. Client retries, re-establishes the connection.
1. Server knows (my own code) that it should not accept new connections, so immediately returns from the RPC handler.
1. The above continues potentially a few times.
1. Server writes GOAWAY, client sees it and stops sending new RPC via this TCP connection. It would establish a new TCP connection to a different backend and proceed normally.

I'd like to change this behavior so that my shutdown code sends GOAWAY and only then signals running RPC handlers to return. I don't see an existing way to achieve this.

### Proposed Solution

Some sort of callback or channel that is closed, not sure.

### Alternatives Considered

Currently I have to resort to this hack:

```go
go func() {
    // good enough? Maybe not, depending on how fast the listener stops and GOAWAY is written to all connections.
    time.Sleep(1*time.Second)
    signalRPCHandlers() // let them know they need to return
}()
server.GracefulStop()
```

**Comment by dfawley** [comment]
cc @ejona86 @markdroth 

I don't think this is specific to Go.  I don't believe any gRPC languages have a way to notify running server RPC handlers when the server is being gracefully shut down, much less about specific events within the life-cycle of that shutdown.

Typically, long-running streams are okay to be hard closed after some grace period.  (The usual shutdown process is: 1. `GracefulStop`, 2. after some hard-coded grace period, hard-`Stop`.)  If your RPCs are sensitive to this failure mode, then you might want to do something like re-establish these streams at a rate higher than that grace period, if you can't redesign them so they are more resilient.

**Comment by ejona86** [comment]
I think this might be Go-specific, although C++ might have something similar.

In Java `shutdown()` only waits until the socket is closed. It doesn't wait for pending RPCs to finish. So you could do `shutdown(); notifyServices(); wait(); shutdownNow()`.

> The usual shutdown process is: 1. GracefulStop, 2. after some hard-coded grace period, hard-Stop

The weird part of that is that (1) has to be a separate goroutine than (2) and (3). In Java, you can use the same thread.

**Comment by ejona86** [comment]
>  I don't believe any gRPC languages have a way to notify running server RPC handlers when the server is being gracefully shut down,

To be clear, Java doesn't have any notification here. But the application can wire it together themselves.

**Comment by markdroth** [comment]
At a high level, I think the cross-language functionality that we want here is to have some way for the application to know when the server has stopped listening on the port and has sent both GOAWAYs on all existing connections, so that there's a guarantee that the application won't see any new streams started.  The application can then do whatever it wants to gracefully shut down the existing streams without worrying about new ones starting.

I don't remember offhand what knobs we have in C++ for this, but it wouldn't surprise me if we need some improvements here, since I know that we have some other known problems related to graceful shutdown.  @yashykt can probably tell you more.

**Comment by ejona86** [comment]
I don't think waiting until sending both GOAWAYs is necessary, or even helpful. You only need to wait until the first GOAWAY is enqueued (doesn't even have to be sent). Let's say you did wait until both GOAWAYs are sent. It would still be racy in the application, as gRPC can have queued notifications/created goroutines that the application hasn't seen yet. Just because gRPC won't see any newly-created RPCs doesn't mean the application won't.

But that is solved without too much effort. You notify all existing RPCs and notify immediately any new RPCs. The important part is that the client receives these responses _after_ the _first_ GOAWAY and that new connections can't be created. That guarantees the client will send any new RPC to a different backend.

grpc-java's `shutdown()` does not wait for the first GOAWAYs to be sent. It just has them enqueued. It only blocks on the listening socket being closed.

**Comment by markdroth** [comment]
It seems a little odd to differentiate between allowing new connections and allowing new streams, since the application really cares about the latter, not the former.  But I do take your point about there being race conditions here in cases where incoming RPCs are already enqueued before getting to the application.  I think individual implementations can decide how strong they want this guarantee to be, as long as there is some reasonable and well-documented way for applications to do this.

**Comment by ash2k** [comment]
Just FYI: for me it would work if `GracefulStop()` was split into two methods: `method1` and `method2`. I would then use them like this:

- Call `method1()`. It closes the listeners, enqueues `GOAWAY` on all existing streams.
- Here I notify the in-flight RPCs (and any future RPCs that I haven't seen yet) that they should return control to gRPC.
- Call `mthod2()`. It waits for all RPC handlers to return, etc.

This looks clean and flexible and doesn't require any goroutines/concurrency.

**Comment by dfawley** [comment]
This doesn't seem like it fixes your primary concern, then.

Your initial concern was that it was racy and you could get new RPCs after signalling that you were about to call `GracefulStop`.  If we add a new function that closes the listeners, then that race would still exist.

```go
// Your current "hack":
go func() {
    time.Sleep(1*time.Second)
    signalRPCHandlers() // let them know they need to return
}()
server.GracefulStop()


// But that might as well be:
signalRPCHandlers()  // Reject any new RPCs
server.GracefulStop()


// Proposed:
server.StopListenersAndDrain()
signalRPCHandlers()  // Reject any new RPCs, which could still occur due to unavoidable races.
```

This is a very marginal improvement.

Slightly nicer is not having to call `GracefulStop` in a goroutine in order to later get the hard stop after a grace period:

```go
// Before:
go func() {
	time.Sleep(30*time.Second) // grace period
	server.Stop()
}()
server.GracefulStop()

// After:
server.StopListenersAndDrain()
time.Sleep(30*time.Second) // grace period
server.Stop()
```

**Comment by ash2k** [comment]
Not only stop listeners (I could do that myself), but also send GOAWAY in `method1`.

**Comment by ash2k** [comment]
Ah, GOAWAY is not per-stream, it's per-TCP connection, right? But, again, presumably if it's queued before it's sent before all the EOFs?

**Comment by dfawley** [comment]
> Ah, GOAWAY is not per-stream, it's per-TCP connection, right?

Correct.  It tells the client to stop creating new RPCs on the connection.  All existing streams on the connection continue unaffected.

> But, again, presumably if it's enqueued before and is sent before all the EOFs?

[Assuming you mean "the end of the stream with status OK" when you say "EOF".]  We do have the ability to make sure the GOAWAY is queued on the connection before returning.  However, new streams may still be created if they are already on the wire by the time the client sees and decides to honor the GOAWAY.

> with a lot of connections it's not that small

Can you quantify the significance of this change to your application?  I.e. have you tried the "might as well be" section from https://github.com/grpc/grpc-go/issues/6830#issuecomment-1841370341, and what is the impact of it?  If we add a new method on the server to do this, what would be better and by how much?

**Comment by ash2k** [comment]
> Assuming you mean "the end of the stream with status OK" when you say "EOF"

Correct.

>  However, new streams may still be created if they are already on the wire by the time the client sees and decides to honor the GOAWAY.

I understand. As I said above, it's ok for my app. It will immediately respond with OK in that case.

> Can you quantify the significance of this change to your application?

Not really, I cannot.

> have you tried the "might as well be" section from https://github.com/grpc/grpc-go/issues/6830#issuecomment-1841370341, and what is the impact of it? If we add a new method on the server to do this, what would be better and by how much?

This is how it was working until recently. Then I changed it to signal the handlers with a delay. I'm not sure how to monitor this. I'm debugging an issue and that's how I stumbled upon this. I changed the shutdown to me "more correct" but it didn't improve the situation with the specific problem I'm debugging. It may have made the shutdown cleaner though, I just don't know how to measure that, sorry.

**Comment by dfawley** [comment]
It's hard to justify complicating our API and spending time and effort on something like this if there aren't good reasons for doing it besides "it would be nice".  While I do agree that it would be nice, it seems to me like the impact is also likely to be very negligible -- a handful of additional new RPCs would be started after signaling the handlers and before closing the listeners, which would be unlikely to cause excessive load on the system or other problems.  The biggest win that I can see is the full graceful shutdown process would be able to look a little cleaner by removing the goroutine, but given that we'll never be able to delete our old API, I think it would be preferable to just have one way of doing things instead of two.

If there are reasons why this would be objectively and measurably better, that would outweigh the cost of adding it, then we can revisit in the future.  Thanks for the suggestion.

**Comment by ash2k** [comment]
> would be unlikely to cause excessive load on the system or other problems

Just to clarify - my concern is not load, it's extra latency because the clients may be in a different geography, very far away. In my case latency is somewhat important and not wasting that roundtrip is a good optimization.

Having said that, I'm fine with the workaround that I have. Thank you for considering this.
